### ISSUE TITLE
Any ideas on how to observe atom changes?

### ISSUE THREAD

**Issue by nicolas6422** [luisanton-io/recoil-nexus#26]
Say I want to setup an observer outside of the react render tree like

```js
import { observe } from 'recoil-nexus';

class Class {
  constructor() {
    observe(someAtom, (oldValue, newValue) => {
      // do something
    })
  }
}
```

Would this be possible?
Figured you'd be the best person to ask 😄

**Comment by luisanton-io** [comment]
Hi, I think I can help but this doesn't look strictly related to this package, could you please post your question on Stack Overflow and link it here?

**Comment by CyberCyclone** [comment]
@luisanton-io is there a reason this isn't part of the package? It seems like a reasonable utility that covers common use cases.

I'm going to try implementing it myself as part of a forked package, but it would be good to see the way you were thinking it should work.

**Comment by CyberCyclone** [comment]
I haven't been able to figure out a solution yet mostly because I can't find a function that takes a callback and also subscribes. As in, `useRecoilCallback` is a once off, it's not a subscription.

I've posted a question on SO: https://stackoverflow.com/questions/76634495/react-recoil-outside-of-react-component-observable-subscriptions

**Comment by luisanton-io** [comment]
HI @CyberCyclone, I [replied to your question](https://stackoverflow.com/a/76643334/11783958).
