### ISSUE TITLE
when will this work with selectors?

### ISSUE THREAD

**Issue by surajsharma** [luisanton-io/recoil-nexus#9]
i see there is no implementation in the API for selectors, please add the same

**Comment by surajsharma** [comment]
currently `setRecoil` does not accept selectors, only atoms, i wonder if there's a way to pass in a settable selectors

**Comment by luisanton-io** [comment]
By definitions `selectors` are read-only since they represent [a piece of derived state](https://recoiljs.org/docs/basic-tutorial/selectors).

[Here](https://codesandbox.io/s/wizardly-euclid-mv9id?file=/src/atoms/loadingSelector.ts
) you can find an updated Sandbox where I highlighted you can successfully retrieve the selectors value using Recoil Nexus - but again, this is read only.

Hope this helps,
L

**Comment by luisanton-io** [comment]
I think I have actually understood now what you are looking for.
You are looking for a way to *read* the selectors' setter so you can use it.

Sounds interesting and I might be trying to figure a way to make it work!

**Comment by Kevin-Shiuan** [comment]
Hi, your library is awesome and I wish to use selector too.

**Comment by luisanton-io** [comment]
Now supported in `v0.5.0`. 
Updated the [loader example](https://github.com/luisanton-io/simple-loader-with-nexus) as well with a simple selector.

Thanks @ha-sash for your helpful contribution!
